# Generated by Django 5.1.7 on 2025-04-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='receiveForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_data', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('supplier', models.CharField(max_length=100)),
                ('received_date', models.DateField()),
            ],
        ),
    ]
