# Generated by Django 5.1.7 on 2025-04-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiveforms',
            name='received_date',
            field=models.IntegerField(),
        ),
    ]
