# Generated by Django 5.1.7 on 2025-04-20 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_receiveforms_received_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='receiveForms',
            new_name='receiveModel',
        ),
    ]
