# Generated by Django 5.1.7 on 2025-04-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_receiveforms_receivemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_dataadd', models.CharField(max_length=100)),
            ],
        ),
    ]
