# Generated by Django 5.1.7 on 2025-04-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_itemsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivemodel',
            name='received_date',
            field=models.DateField(),
        ),
    ]
