# Generated by Django 5.1.7 on 2025-04-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_receivemodel_received_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
            ],
        ),
    ]
