# Generated by Django 5.1.7 on 2025-05-03 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_inventory_alter_receivemodel_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
